from typing import Protocol

class LogicCallbacks(Protocol):
    def on_handshake(self, peer_id: int) -> None: ...
    def on_disconnect(self) -> None: ...
    def on_choke(self) -> None: ...
    def on_unchoke(self) -> None: ...
    def on_interested(self) -> None: ...
    def on_not_interested(self) -> None: ...
    def on_have(self, index: int) -> None: ...
    def on_bitfield(self, bits: bytes) -> None: ...
    def on_request(self, index: int) -> None: ...
    def on_piece(self, index: int, data: bytes) -> None: ...


class WireCommands(Protocol):
    def send_handshake(self, peer_id: int) -> None: ...
    def send_choke(self) -> None: ...
    def send_unchoke(self) -> None: ...
    def send_interested(self) -> None: ...
    def send_not_interested(self) -> None: ...
    def send_have(self, index: int) -> None: ...
    def send_bitfield(self, bits: bytes) -> None: ...
    def send_request(self, index: int) -> None: ...
    def send_piece(self, index: int, data: bytes) -> None: ...
    def close(self) -> None: ...

